version: "2.4"
services:
  pgdata:
    image: "tianon/true"
    volumes:
    - /var/lib/postgresql/data
  cache:
    image: "tianon/true"
    volumes:
    - /data/cache
  postgres:
    image: "osmpostgres"
    mem_limit: 10000000000
    volumes_from:
     - pgdata
    ports:
     - "5432"
    environment:
      POSTGRES_PASSWORD: noise
  import-osm:
    image: "import-osm"
    command: ./import-osm.sh
    volumes:
     - ./data:/data/import
    volumes_from:
     - cache
    environment:
      POSTGRES_PORT_5432_TCP_ADDR: postgres
    links:
     - postgres:postgres
  tileserver:
    container_name: tileserver
    image: klokantech/tileserver-gl:v2.6.0
    ports:
      - 8080:80
    volumes:
      - ./data:/data
  mapbox-studio:
    image: "lukasmartinelli/osm-noise-pollution:mapbox-studio"
    mem_limit: 500000000
    volumes:
     - ./src/vector-datasource:/projects/vector-datasource.tm2source
    links:
     - postgres:postgres
    ports:
     - "3000:3000"
  export-vectortiles:
    image: "lukasmartinelli/osm-noise-pollution:export-vectortiles"
    volumes:
     - ./data:/data/export
     - ./src/vector-datasource:/data/tm2source
    links:
     - postgres:db
    environment:
      POSTGRES_PORT_5432_TCP_ADDR: postgres
      DB_PORT_5432_TCP_ADDR: postgres
      DB_PORT_5432_TCP_PORT: 5432
      BBOX: "5.98865807458 47.3024876979 15.0169958839 54.983104153"
      MIN_ZOOM: "10"
      MAX_ZOOM: "10"
  serve-vectortiles:
    image: "klokantech/tileserver-php"
    volumes:
     - ./data:/var/www
    ports:
     - "8080:80"
